### ISSUE TITLE
extra temperature sensors

### ISSUE THREAD

**Issue by tgribble** [caitken-com/node-red-contrib-daikin-api#2]
hi - thanks for the work on this node red project

i have the BRP15B61 LAN device with a BRC24Z8B zone controller which allows 2 extra temperature sensors and an extra remote controller totalling 5 x temperature sensors in the HVAC system. 

- return duct temperature sensor
- main controller built in temperature sensor
- main controller built in temperature sensor
- extra temperature sensor 1
- extra temperature sensor 2

i am trying to locate in the information get/set where the sensed temperature location can be found? i would like to have the node red change the sensed temperature periodically to have the HVAC more even in the house by switching the sensed temperature position

is there any further sensed information available from the BRP15B61 that might contain that information? if so where would it be ? how can i interrogate the BRP15B61 to look for this ?

thanks

**Comment by tgribble** [comment]
figured out the zone names: - now looking for the temperature sensors

{
   "cmd": "getRaw",
   "endpoint":"get_zone_setting",
   "data": null
}

then url decode the results which in my case are : ( https://www.urldecoder.org/ ) 

FROM ret=OK,zone_name=%4d%65%64%69%61%20%52%6f%6f%6d%3b%50%6f%6f%6c%20%52%6f%6f%6d%3b%48%61%72%70%65%72%73%20%52%6f%6f%6d%3b%47%61%72%64%65%6e%20%52%6f%6f%6d%3b%2d%3b%2d%3b%2d%3b%2d,zone_onoff=0%3b0%3b0%3b1%3b0%3b0%3b0%3b0

TO 
ret=OK,zone_name=Media Room;Pool Room;Harpers Room;Garden Room;-;-;-;-,zone_onoff=0;0;0;1;0;0;0;0

**Comment by caitken-com** [comment]
Hi @tgribble.
`getRaw` should return JSON results within NodeRed. For example this is my request and results:

### Inject payload:

```json
{
    "cmd": "getRaw",
    "endpoint": "get_sensor_info",
    "data": null
}
```
### Debug node results:
```json
{
   "ret": "OK"
   "err": "0"
   "htemp": "28"
   "otemp": "-"
}
```

<img width="666" alt="Screenshot 2023-12-30 at 6 29 23 pm" src="https://github.com/caitken-com/node-red-contrib-daikin-api/assets/40314295/bf8eb439-62b3-4713-a52f-359d8f3de39c">

**Comment by caitken-com** [comment]
I don't have the extra sensors or vent controller. But I'm happy to help anyway I can. If you have [Discord](https://discord.gg/uvYac5u), we can chat in real time to see if we can get anywhere :)

**Comment by caitken-com** [comment]
Hi @tgribble.
I see the issue now. I wasn't decoding URL params. I am now: See version `1.1.0`

### Request:
```json
{
    "cmd": "getRaw",
    "endpoint": "get_zone_setting"
}
```
### Response:
```json
{
    "ret": "OK",
    "zone_name": [
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-"
    ],
    "zone_onoff": [
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0"
    ]
}
```
### Request:
```json
{
    "cmd": "getZoneSetting"
}
```
### Response:
```json
{
    "Zones": [
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-"
    ],
    "On": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ]
}
```

**Comment by caitken-com** [comment]
Hi @tgribble.

I've added a new command to set zone settings, See version `1.3.0`

```json
{
    "cmd": "setZoneSetting",
    "On": [true,false,false,false,false,false,false,false]
}
```
